field.perspective.value:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: text
      label: 'Text'
perspective.settings:
  type: config_object
  label: 'Perspective settings'
  mapping:
    perspective:
      type: mapping
      mapping:
        google_api_url:
          type: text
          label: 'Google API URL:'
        google_api_key:
          type: text
          label: 'Google API Key:'
        tolerance:
          type: integer
          label: 'Toxocity tolerance:'
        error_text:
          type: text
          label: 'Error text:'
        use_ajax:
          type: boolean
          label: 'Use Ajax:'
